name: damask_parse_env
channels:
  - conda-forge
dependencies:
  - python=3.10 # conda-unpack does not work on Windows with 3.11 for some reason
  - pip
  - pip:
      - matflow-new
      - scipy # damask (required by damask-parse) needs scipy, but this is not resolved for some reason
      - damask-parse
