# as many matflow environments as possible in one conda env
name: matflow_full_env
channels:
  - conda-forge
dependencies:
  - python=3.10 # conda-unpack does not work on Windows with 3.11 for some reason
  - bcrypt        # ! these packages are requirements of the below pip dependencies, but I think
  - cryptography  # !   conda lock does not resolve the correct manylinux wheels on our old CentOS
  - pillow        # !   docker image, meaning there is a hash mismatch when trying to create the
  - pyzmq=26.4.0  # !   environment :(
  - pip
  - pip:
      - jupyter
      - matflow-new      
      - damask==3.0.0a7.post0 # our use of Grid.scale in MatFlow not compatible with latest damask package
      - damask-parse
      - formable
      - numpy<2
