# as many matflow environments as possible in one conda env:
#  - damask_parse
#  - formable
#  - matflow
#  TODO: add dream3D?
# this is the same as `matflow_damask_full_env` but without the damask conda package
name: matflow_full_env
channels:
  - conda-forge
dependencies:
  - python=3.10 # conda-unpack does not work on Windows with 3.11 for some reason
  - pip
  - pip:
      - jupyter
      - matflow-new      
      - damask==3.0.0a7.post0 # our use of Grid.scale in MatFlow not compatible with latest damask package
      - damask-parse
      - formable
      - numpy<2
