name: release-conda-pack-env
on:
  workflow_dispatch:
    inputs: 
      environment:
        type: choice
        description: Choose which environment to conda-pack
        options:
          - damask_parse_env
            
jobs:
  conda-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: mamba-org/setup-micromamba@v1
      - run: micromamba install -c conda-forge conda-lock
      - run: conda-lock lock ${{ github.event.inputs.environment }}/environment.yaml
