name: release-conda-pack-env
on:
  workflow_dispatch:
    inputs: 
      environment:
        type: choice
        description: Choose which environment to conda-pack
        options:
          - damask_parse_env
            
jobs:
  conda-lock-and-pack:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
      - name: Create a base micromamba environment and install conda-lock
        run: |
          micromamba create -n base_env -c conda-forge python conda-lock conda-pack
      - name: Run conda-lock
        run: |
          micromamba activate base_env
          conda-lock lock --file ${{ github.event.inputs.environment }}/environment.yaml --lockfile ${{ github.event.inputs.environment }}-conda-lock.yaml
      - name: Create and pack environment
        run: |
          micromamba create --name ${{ github.event.inputs.environment }} --file ${{ github.event.inputs.environment }}-conda-lock.yaml
          micromamba activate base_env
          conda pack -n ${{ github.event.inputs.environment }}
      - name: Upload conda-lock file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.environment }}-conda-lock.yaml
          path: ${{ github.event.inputs.environment }}-conda-lock.yaml
      - name: Upload conda-packed environment 
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.environment }}.tar.gz
          path: ${{ github.event.inputs.environment }}.tar.gz
