name: release-conda-pack-env
on:
  workflow_dispatch:
    inputs: 
      environment:
        type: choice
        required: true
        description: Choose which environment to conda-pack
        options:
          - damask_parse_env
          - damask_env
      pack_linux:
        description: "Loack and build a packed env for Linux?"
        required: true
        type: boolean
        default: true
      pack_macos:
        description: "Lock and build a packed env for macOS?"
        required: true
        type: boolean
        default: true
      pack_windows:
        description: "Lock and build a packed env for Windows?"
        required: true
        type: boolean
        default: true
            
jobs:
  conda-lock:
    if: github.event.inputs.pack_linux == 'true' || github.event.inputs.pack_macos == 'true' || github.event.inputs.pack_windows == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    container:  
      image: ghcr.io/hpcflow/centos7-micromamba:latest
    steps:
      - uses: actions/checkout@v3
      - name: Run conda-lock
        run: |
          micromamba --root-prefix /root/micromamba run -n base_env \
           conda-lock lock \
           --platform \
              ${{ github.event.inputs.pack_linux == 'true' && 'linux-64' || '' }} \
              ${{ github.event.inputs.pack_macos == 'true' && 'osx-64' || '' }} \
              ${{ github.event.inputs.pack_windows == 'true' && 'win-64' || '' }} \
           --file ${{ github.event.inputs.environment }}/environment.yaml \
           --lockfile ${{ github.event.inputs.environment }}-conda-lock.yaml
      - name: Upload conda-lock file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.environment }}-conda-lock.yaml
          path: ${{ github.event.inputs.environment }}-conda-lock.yaml
  
  conda-pack-linux:
    if: github.event.inputs.pack_linux == 'true'
    needs: [conda-lock]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    container:  
      image: ghcr.io/hpcflow/centos7-micromamba:latest
    steps:
      - name: Download conda-lock file
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.inputs.environment }}-conda-lock.yaml
      - name: Create the environment
        run: |
          micromamba --root-prefix /root/micromamba create --name ${{ github.event.inputs.environment }}-linux --file ${{ github.event.inputs.environment }}-conda-lock.yaml
      - name: Pack the environment
        run: |          
          micromamba --root-prefix /root/micromamba run -n base_env conda-pack --prefix /root/micromamba/envs/damask_parse_env-linux
      - name: Upload conda-packed environment 
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.environment }}-linux.tar.gz
          path: ${{ github.event.inputs.environment }}-linux.tar.gz
    
  conda-pack-windows:
    if: github.event.inputs.pack_windows == 'true'
    needs: [conda-lock]
    runs-on: windows-latest
    steps:
      - name: Download conda-lock file
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.inputs.environment }}-conda-lock.yaml
      - name: Download micromamba executable
        run: |
          Invoke-WebRequest -UseBasicParsing https://github.com/mamba-org/micromamba-releases/releases/latest/download/micromamba-win-64 -OutFile micromamba-win-64.exe
      - name:  Create a base environment including conda-pack
        run: |
          .\micromamba-win-64.exe create -y --name base_env -c conda-forge python conda-pack conda-lock
      - name: Create the environment
        run: |
          .\micromamba-win-64.exe create -y --name ${{ github.event.inputs.environment }}-win --file ${{ github.event.inputs.environment }}-conda-lock.yaml
      - name: Pack the environment
        run: |
          .\micromamba-win-64.exe run --name base_env conda-pack --prefix $HOME\micromamba\envs\${{ github.event.inputs.environment }}-win
      - name: Upload conda-packed environment 
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.environment }}-win.tar.gz
          path: ${{ github.event.inputs.environment }}-win.tar.gz

  conda-pack-macos:
    if: github.event.inputs.pack_macos == 'true'
    needs: [conda-lock]
    runs-on: macos-latest
    steps:
      - name: Download conda-lock file
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.inputs.environment }}-conda-lock.yaml
      - name: Download and extract micromamba executable
        run: |
          curl -Ls https://micro.mamba.pm/api/micromamba/osx-64/latest | tar -xvj bin/micromamba
      - name:  Create a base environment including conda-pack
        run: |
          ./bin/micromamba create -y --name base_env -c conda-forge python conda-pack conda-lock
      - name: Create the environment
        run: |
          ./bin/micromamba create -y --name ${{ github.event.inputs.environment }}-macos --file ${{ github.event.inputs.environment }}-conda-lock.yaml
      - name: Pack the environment
        run: |
          ./bin/micromamba run --name base_env conda-pack --name ${{ github.event.inputs.environment }}-macos
      - name: Upload conda-packed environment 
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.environment }}-macos.tar.gz
          path: ${{ github.event.inputs.environment }}-macos.tar.gz
