name: release-conda-pack-env
on:
  workflow_dispatch:
    inputs: 
      environment:
        type: choice
        description: Choose which environment to conda-pack
        options:
          - damask_parse_env
            
jobs:
  conda-lock:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    container:  
      image: ghcr.io/hpcflow/centos7-micromamba:latest
    steps:
      - uses: actions/checkout@v3
      - name: Run conda-lock
        run: |
          micromamba --root-prefix /root/micromamba run -n base_env conda-lock lock --file ${{ github.event.inputs.environment }}/environment.yaml --lockfile ${{ github.event.inputs.environment }}-conda-lock.yaml
      - name: Upload conda-lock file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.environment }}-conda-lock.yaml
          path: ${{ github.event.inputs.environment }}-conda-lock.yaml
  
  conda-pack-linux:
    needs: [conda-lock]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    container:  
      image: ghcr.io/hpcflow/centos7-micromamba:latest
    steps:
      - name: Download conda-lock file
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.inputs.environment }}-conda-lock.yaml
      - name: Create the environment
        run: |
          micromamba --root-prefix /root/micromamba create --name ${{ github.event.inputs.environment }}-linux --file ${{ github.event.inputs.environment }}-conda-lock.yaml
      - name: Pack the environment
        run: |          
          micromamba --root-prefix /root/micromamba run -n base_env conda-pack --prefix /root/micromamba/envs/damask_parse_env-linux
      - name: Upload conda-packed environment 
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.environment }}-linux.tar.gz
          path: ${{ github.event.inputs.environment }}-linux.tar.gz
    
  conda-pack-windows:
    needs: [conda-lock]
    runs-on: windows-latest
    steps:
      - name: Download conda-lock file
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.inputs.environment }}-conda-lock.yaml
      - name: Download micromamba executable
        run: |
          Invoke-WebRequest -UseBasicParsing https://github.com/mamba-org/micromamba-releases/releases/latest/download/micromamba-win-64 -OutFile micromamba-win-64.exe
      - name:  Create a base environment including conda-pack
        run: |
          .\micromamba-win-64.exe create -y --name base_env -c conda-forge python conda-pack conda-lock
      - name: Create the environment
        run: |
          .\micromamba-win-64.exe create -y --name ${{ github.event.inputs.environment }}-win --file ${{ github.event.inputs.environment }}-conda-lock.yaml
      - name: Pack the environment
        run: |
          .\micromamba-win-64.exe run --name base_env conda-pack --prefix ~/micromamba/envs/${{ github.event.inputs.environment }}-win
      - name: Upload conda-packed environment 
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.environment }}-win.tar.gz
          path: ${{ github.event.inputs.environment }}-win.tar.gz
