name: release-conda-pack-env
on:
  workflow_dispatch:
    inputs: 
      environment:
        type: choice
        description: Choose which environment to conda-pack
        options:
          - damask_parse_env
            
jobs:
  conda-lock:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
      - run: |
          micromamba create -n base_env python
          micromamba activate base_env
          micromamba install -c conda-forge conda-lock
      - run: |
          conda-lock lock ${{ github.event.inputs.environment }}/environment.yaml
